<?php
// In the migration file generated by Laravel
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddTotalPriceToFoodOrderTable extends Migration
{
    public function up()
    {
        Schema::table('food_order', function (Blueprint $table) {
            $table->decimal('total_price', 8, 2)->after('quantity');  // Add total_price after quantity
        });
    }

    public function down()
    {
        Schema::table('food_order', function (Blueprint $table) {
            $table->dropColumn('total_price');
        });
    }
}

